{% set version = "3.3.0" %}

package:
  name: spdlib
  version: {{ version }}

source:
  url: https://bitbucket.org/petebunting/spdlib/downloads/spdlib-{{ version }}.tar.gz
  sha256: ded350c5eedb7b3b92a84a1e2d6dfa4c6f9ecb09bd83f0fcfb7fe17c1595b9c7
  patches:
    - python_numeric.cpp.patch
    - winboost.patch  # [win]
    - pyboost.patch
    - nocpp98.patch

build:
    number: 2
    # CGAL etc do not support earlier than vc14
    skip: True  # [win and py<35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - hdf5
    - xerces-c
    - gsl
    - libgdal
    - geos
    - cgal
    - lastools
  run:
    - boost-cpp
    - hdf5
    - xerces-c
    - gsl
    - libgdal
    - geos
    - cgal
    - lastools

test:
  commands:
    - if not exist %LIBRARY_BIN%\\libspd.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libspd.lib exit 1  # [win]
    - test -f $PREFIX/lib/libspd.so                  # [linux]
    - test -f $PREFIX/lib/libspd.dylib               # [osx]
    - spdtranslate -h

about:
  home: http://www.spdlib.org
  license: GPLv3
  summary: The Sorted Pulse Data Library (SPDLib) provides a format for storing and tools for processing discrete return and full waveform LiDAR data from airborne and terrestrial sensors.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
    - armstonj
