travis:
  secure:
    BINSTAR_TOKEN: kLCHrP5iLFTaAFGB5r3gye9swU3m54mAzpbtMWMjgX84XP8ZUlLTRD9y5msSnXOZ2Q9voRikB00917I6TaTHCg4FLjBBKchdEc8koZ6Q+ZEGyKkMwLPJVhPw+NreUxove+jIv/1sCtQ4Ephzc0/LleEDcr6KUAlbakjgKakwlJeKtoF7EppPHw5k5mEOkMcm7JlMOshNi5OceAV+au+cNi5wE36S7EhXi4Kph/uGrabYJUtVJbHrE2kG7P4fnZfgjKb+HsvHnnCyJNRfygcK0+vLoLixnyXX5+1v9s5NMsZoHRi2z7G1MscWMY5sS+qE0S5Yggzn9ogqE4J2RZl+FwqmOx0Rfb6L31JYKYCNysAJRjVEoWGVjOw32sYLkyoD7BDRcXALGMn86RZ0+2ZETy1MEZwySIVIxqGrR0x4e9RTKK1N6WboXWiZe220BGfsrt17YWgrx+Zwar+zidYBjaX3ofTCJRa1e/+2dH5bEYNlpwIw3oSdIZNsYIaeyU3i1MFJzasztywTvQDeDbJXRyXTVtmWpj/qWG8ai1GreS7fhE4PNLAlHYLMk6km2eSvDHnNUVfEfZobwmFU7S5XZgPvAvBGAeHbTpRHSEl5W79c5IfFKptcOSMblE+NUuG+iWO2h08K/sAcBsWMre3m89NFBGyX+XWqhFaRijDpaD8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
